version: '3.5'
services:
  web:
    image: openproject/community:11.3.4
    depends_on:
      - postgres
      - memcached
    ports:
      - "8090:80"
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./data:/var/db/openproject
    environment:
      DATABASE_URL: "postgres://opuser:oppassword@postgres:5432/openproject?pool=10&encoding=unicode&timeout=5000&reconnect=true"
      SECRET_KEY_BASE: secret_key_base
      CACHE_MEMCACHE_SERVER: memcached
      CACHE_NAMESPACE: openproject
    restart: always
  postgres:
    image: postgres:9.6-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: openproject
      POSTGRES_USER: opuser
      POSTGRES_PASSWORD: oppassword
    restart: always
  memcached:
    image: memcached:1.5.7-alpine
    restart: always
volumes:
  pg-data:
